#!/usr/bin/python
# -*- coding: utf-8 -*- 

import os
import re
import datetime
import pytz
import shutil
import sys
from optparse import OptionParser

from django.conf import settings

from spud import models
from spud import media

def rename(pk,name):
    p = models.photo.objects.get(pk=pk)
    p.move(name)

def main():
        spud_file = u"%s/%s"%(settings.IMAGE_PATH,".spud.txt")
        if not os.path.exists(spud_file):
            raise RuntimeError("Cannot find spud file. Is '%s' mounted???"%(settings.IMAGE_PATH))

        parser = OptionParser()
        (options, args) = parser.parse_args()

        rename(args[0],args[1])
        return 0

if __name__ == "__main__":
#    sys.exit(main())

    for photo in models.photo.objects.filter(name__startswith="F"):
        print photo.name
        m = media.get_media(photo.get_orig_path())
        src_timezone = pytz.timezone("Australia/Melbourne")
        dst_timezone = pytz.timezone(photo.timezone)
        dt = m.get_datetime(src_timezone,dst_timezone)
        print photo.datetime
        photo.datetime = dt.astimezone(pytz.utc).replace(tzinfo=None)
        print photo.datetime
        print
        photo.move()
