version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - 6.2.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
