language: python
sudo: false
python:
 - 3.5
 - 3.6

env:
 - DJANGO_VERSION=1.11.3 DATABASE_URL=postgres://postgres@/spud
 - DJANGO_VERSION=master DATABASE_URL=postgres://postgres@/spud

 - DJANGO_VERSION=1.11.3 DATABASE_URL=sqlite://
 - DJANGO_VERSION=master DATABASE_URL=sqlite://

install:
# Install django master or version
  - bash -c "if [[ \"$DJANGO_VERSION\" == 'master' ]]; then pip install 'https://github.com/django/django/archive/master.tar.gz'; else pip install Django==$DJANGO_VERSION; fi; "
# Install other dependancies
  - pip install -rrequirements/tests.txt

script:
  - python ./setup.py --version
  - py.test --cov=spud


matrix:
  fast_finish: true
  allow_failures:
      - env: DJANGO_VERSION=master DATABASE_URL=postgres://postgres@/spud
      - env: DJANGO_VERSION=master DATABASE_URL=sqlite://
