language: python
sudo: false
python:
 - 3.5
 - 3.6

env:
 - DATABASE_URL=postgres://postgres@/spud
 - DATABASE_URL=sqlite://

install:
 - pip install -rrequirements/tests.txt

script:
 - python ./setup.py --version
 - py.test --cov=spud
