language: python
sudo: false
python:
 - 3.5
 - 3.6
 - 3.7

env:
 - DATABASE_URL=postgres://postgres@/spud

install:
 - pip install -rrequirements/tests.txt

before_script:
  - psql -c 'create database spud;' -U postgres

script:
 - isort -rc --check --diff spud
 - flake8
 - python ./manage.py makemigrations --settings=spud.tests.settings --check --dry-run
 - python ./manage.py migrate --settings=spud.tests.settings
 - python ./setup.py --version
 - py.test --cov=spud

jobs:
  include:
    - stage: deploy
      if: branch = master and type = push
      install:
      script:
      - docker build
            --file "Dockerfile"
            --tag "brianmay/spud:latest"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "brianmay/spud:latest"
