language: python
sudo: false
python:
 - 2.7
 - 3.4
 - 3.5

env:
 - DJANGO_VERSION=1.8.17 DATABASE_URL=postgres://postgres@/spud
 - DJANGO_VERSION=1.9.12 DATABASE_URL=postgres://postgres@/spud
 - DJANGO_VERSION=1.10.5 DATABASE_URL=postgres://postgres@/spud
 - DJANGO_VERSION=master DATABASE_URL=postgres://postgres@/spud

 - DJANGO_VERSION=1.8.17 DATABASE_URL=mysql://root:@localhost/spud
 - DJANGO_VERSION=1.9.12 DATABASE_URL=mysql://root:@localhost/spud
 - DJANGO_VERSION=1.10.5 DATABASE_URL=mysql://root:@localhost/spud
 - DJANGO_VERSION=master DATABASE_URL=mysql://root:@localhost/spud

 - DJANGO_VERSION=1.8.17 DATABASE_URL=sqlite://
 - DJANGO_VERSION=1.9.12 DATABASE_URL=sqlite://
 - DJANGO_VERSION=1.10.5 DATABASE_URL=sqlite://
 - DJANGO_VERSION=master DATABASE_URL=sqlite://

install:
# Install django master or version
  - bash -c "if [[ \"$DJANGO_VERSION\" == 'master' ]]; then pip install 'https://github.com/django/django/archive/master.tar.gz'; else pip install Django==$DJANGO_VERSION; fi; "
# Install database drivers
  - bash -c "if [[ $DATABASE_URL = postgres* ]]; then pip install psycopg2==2.6.1; fi; "
  - bash -c "if [[ $DATABASE_URL = mysql* ]]; then pip install mysqlclient==1.3.7; fi; "
# Install other dependancies
  - pip install -rrequirements-tests.txt

script:
  - python ./setup.py --version
  - py.test --cov=spud


matrix:
  fast_finish: true
  allow_failures:
      - env: DJANGO_VERSION=master DATABASE_URL=postgres://postgres@/spud
      - env: DJANGO_VERSION=master DATABASE_URL=mysql://root:@localhost/spud
      - env: DJANGO_VERSION=master DATABASE_URL=sqlite://
