language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy

env:
 - DJANGO_VERSION=1.7.10
 - DJANGO_VERSION=1.8

install:
    - travis_retry pip install -q Django==$DJANGO_VERSION pytest pytest-django djangorestframework django-pipeline django-ajax-selects

script:
  - py.test
