# Generated by Django 2.0.2 on 2018-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spud', '0001_squashed_0015_auto_20170608_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='focus_dist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
