# Generated by Django 2.0.2 on 2018-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spud', '0002_auto_20180330_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
