# Generated by Django 2.1.2 on 2019-03-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spud', '0003_auto_20180402_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_key', models.CharField(max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('mime_type', models.CharField(max_length=20)),
                ('dir', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('is_video', models.BooleanField()),
                ('sha256_hash', models.BinaryField(max_length=32, unique=True)),
                ('num_bytes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='photo_file',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spud.photo'),
        ),
        migrations.AlterUniqueTogether(
            name='photo_file',
            unique_together={('photo', 'size_key', 'mime_type'), ('dir', 'name')},
        ),
    ]
