# Generated by Django 2.1.7 on 2019-04-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spud', '0008_auto_20190321_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo_file',
            unique_together={('dir', 'name'), ('photo', 'size_key', 'mime_type')},
        ),
        migrations.AddIndex(
            model_name='photo_file',
            index=models.Index(fields=['size_key', 'sha256_hash'], name='spud_photo__size_ke_a061df_idx'),
        ),
    ]
