# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spud', '0014_auto_20160501_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_relation',
            options={'ordering': ['photo_1', 'photo_2']},
        ),
    ]
